name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Initialize Capacitor
        run: |
          npx cap init "Turco Mahjong" "com.kenansalim.mahjong" --web-dir www
          npx cap add android

      - name: Build Android App
        run: |
          npx cap copy
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: turco-mahjong-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
